name: 3D Profile Contribution
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          userName: vishwa-Ansh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update 3D contribution graph"
